<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title> Sistema de Información (ADSI-NOTAS) </title>
	<link rel="stylesheet" href="<?php echo $url_css;?>bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo $url_css;?>fontawesome-all.min.css">
	<link rel="stylesheet" href="<?php echo $url_css;?>custom.css">


